POST http://localhost:8080/dwarfs
Content-Type: application/json

{
    "dwarf" : "rahuldogra",
    "redirect": "https://www.rahuldogra.dev/",
    "random": false
}

###
POST http://localhost:8080/dwarfs
Content-Type: application/json

{
    "dwarf" : "rahuldogra",
    "redirect": "https://www.rahuldogra.dev/",
    "random": true
}

###
GET http://localhost:8080/dwarfs


###
GET http://localhost:8080/dwarfs/2

###
PATCH http://localhost:8080/dwarfs
Content-Type: application/json

{
    "id" : 2,
    "dwarf" : "rahuldogra",
    "redirect": "https://www.github.com/irahuldogra",
    "random": false
}

###
DELETE http://localhost:8080/dwarfs/1